name: CICD

on:
  push:
    branches: [deploy-v1]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login to Docker hub
#        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build -t demo-cicdwithdocker .
      - name: Publish image to docker hub
        run: docker push demo-cicdwithdocker:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull demo-cicdwithdocker:latest
      - name: Delete old container
        run: docker rm -f springboot-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-container demo-cicdwithdocker